//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BorrowRecord()
        {
            this.BorrowDetails = new HashSet<BorrowDetail>();
        }
    
        public int RecordId { get; set; }
        public Nullable<int> ReaderId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowDetail> BorrowDetails { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
